import type {SeedCase} from './types'

// Cases 16-30: extraterrestrial (16-19), ghost (20-24), spirit and jinn (25-27), occult (28-30).
// Spirit cases (25-27) are faith-sensitive: never auto-debunked, humour never aimed at a belief.
// Societies are invented. No real groups, religions or people appear.
export const CASES_B: SeedCase[] = [
  {
    n: 16, title: 'Small grey figure in the wash behind the range', category: 'extraterrestrial', subject: 'grey-humanoid',
    region: 'area51', offset: [-0.02, 0.06], place: 'Dry wash south of the perimeter road',
    observedAt: '2026-04-11T04:40:00Z', witness: 'E60B', light: 'night', weather: 'clear', distance: 35, duration: 15,
    description: 'Witness reports a small grey-skinned figure, approximately 1.2 metres tall, standing in a dry wash. Large dark eyes. It did not react to the vehicle headlights and remained motionless until the witness reversed. The witness is the same person as in Cases 15 and 19 and has been asked whether they are aware of the pattern. They are.',
    evidence: [
      {kind: 'testimony', quote: 'It was not afraid of me. That was the worst part.', speaker: 'Witness'},
    ],
    plausibility: 44, flags: ['low-detail', 'possible-misidentification'],
    summary: 'Small motionless figure at night; a coyote, an owl on a post or a survey marker cannot be excluded.',
    memo: 'A motionless figure at 35 metres in headlights is a familiar misidentification of a survey stake or a large bird. The witness’s track record on the Bureau’s files is otherwise good. The file is held for the Director. Recommended: Director’s review.',
  },
  {
    n: 17, title: 'Tall visitor offering reassurance', category: 'extraterrestrial', subject: 'nordic-humanoid',
    region: 'sedona-az', offset: [-0.02, 0.04], place: 'Trailhead above Boynton Canyon',
    observedAt: '2024-04-18T15:30:00Z', witness: '53D7', light: 'daylight', weather: 'clear', distance: 6, duration: 240,
    description: 'Witness reports meeting a tall, fair-haired man on a trail who spoke calmly about "the coming changes" and advised the witness to "be kind to your neighbours". The man was approximately 2 metres tall. He left without walking. Witness later found that the trail has a well-known guide who runs a wellness retreat and is 6 feet 6.',
    evidence: [
      {kind: 'testimony', quote: 'He was very kind. It was slightly too much.', speaker: 'Witness'},
    ],
    plausibility: 22, flags: ['known-hoax-pattern', 'low-detail'],
    summary: 'Tall local trail guide. The advice is sound and unrelated to any extraterrestrial matter.',
    memo: 'A tall, calm man giving encouraging advice on a trail in Sedona is more probably a retreat guide than a visitor from elsewhere. The Bureau does not dispute the advice. The witness is asked to be kind to the guide. Recommended: Director’s review.',
    verdict: 'debunked', verdictBy: 'director', directorNote: 'Local wellness guide, 6 ft 6. The advice was good. Closed.',
  },
  {
    n: 18, title: 'Insectoid figure at the roadside, unmoving', category: 'extraterrestrial', subject: 'mantis-type-humanoid',
    region: 'rachel-nv', offset: [0.03, 0.12], place: 'Shoulder of State Route 375',
    observedAt: '2026-06-03T09:15:00Z', witness: '8B1A', light: 'night', weather: 'clear', distance: 20, duration: 30,
    description: 'Witness reports a tall, thin figure standing at the roadside in the headlights. Triangular head, long limbs, completely still. As the vehicle passed, the figure rotated its head to follow. The witness reports being unable to move the vehicle for a further 30 seconds. Passenger asleep throughout, and now unhelpful.',
    evidence: [
      {kind: 'testimony', quote: 'It rotated its head to follow us. That is not a stick.', speaker: 'Witness'},
      {kind: 'photo', key: 'c18-figure', caption: 'Thin figure at the edge of the headlight beam'},
    ],
    plausibility: 71, flags: ['strong-detail'],
    summary: 'Specific movement detail at close range, matching the subject file.',
    memo: 'The head rotation is the item of interest: it distinguishes this from a Joshua tree, which is the more common candidate in the area. The witness was alert and specific. The Bureau has requested no explanation for the passenger. Recommended for investigation.',
  },
  {
    n: 19, title: 'Grey figure and a light in the sky, same hour', category: 'extraterrestrial', subject: 'grey-humanoid',
    region: 'area51', offset: [0.02, -0.03], place: 'Perimeter viewing area',
    observedAt: '2025-12-05T04:10:00Z', witness: 'E60B', light: 'night', weather: 'clear', distance: 80, duration: 70,
    description: 'Witness reports a small grey figure approaching the fence line and a bright stationary light in the sky above it. Both departed within 70 seconds. Witness has filed Cases 15 and 16 and states, with dignity, that they are not enjoying this.',
    evidence: [
      {kind: 'testimony', quote: 'I go for the desert. This keeps happening.', speaker: 'Witness'},
      {kind: 'photo', key: 'c19-light', caption: 'Stationary light above the fence line'},
    ],
    plausibility: 80, flags: ['strong-detail', 'multiple-witnesses'],
    summary: 'Figure and aerial light in the same 70-second window, corroborated by a second observer.',
    memo: 'A second observer independently recorded the light. The figure was seen by the witness alone. Together with two earlier files, this witness now has the most complete record on the Bureau’s books at this site. Recommended for investigation.',
    verdict: 'classified', note: 'Light corroborated by a second observer. Figure unverified but consistent. Filed as unexplained.',
  },
  {
    n: 20, title: 'Woman in grey on the stair of the vaults', category: 'ghost', subject: 'grey-lady',
    region: 'edinburgh-uk', offset: [-0.002, 0.004], place: 'South Bridge vaults, guided tour route',
    observedAt: '2024-11-02T20:20:00Z', witness: 'F2E4', light: 'artificial', weather: 'clear', distance: 8, duration: 20,
    description: 'Witness, a tour guide, observed a woman in grey period dress standing on the stair at the end of the group. She was seen by the witness and by two tourists. The figure did not appear to touch the steps and vanished when a torch was pointed at her. The two tourists have provided written statements and a small amount of tea.',
    evidence: [
      {kind: 'testimony', quote: 'Two of us saw her. We are both quite sure.', speaker: 'Tourist'},
      {kind: 'sound', description: 'A soft footfall on stone, with no visible person.', seconds: 3},
    ],
    plausibility: 79, flags: ['strong-detail', 'multiple-witnesses'],
    summary: 'Three independent observers, consistent description, well-documented location.',
    memo: 'Three observers agree on dress, position and manner of departure. The location has a long file history and all earlier reports describe the same stair. The guide reported it without embellishment. Recommended for investigation.',
    verdict: 'classified', note: 'Three consistent statements. Location file matches. Filed as unexplained.',
  },
  {
    n: 21, title: 'Dark shape in a doorway of the guest room', category: 'ghost', subject: 'shadow-figure',
    region: 'new-orleans-la', offset: [0.004, 0.006], place: 'Guesthouse in the French Quarter',
    observedAt: '2023-08-13T07:30:00Z', witness: '3C68', light: 'night', weather: 'clear', distance: 4, duration: 10,
    description: 'Guest reports a man-shaped silhouette in the bedroom doorway at approximately 02:30. The shape was darker than the corridor behind it and left when the witness turned on a lamp. A search of the room and corridor found no one. The hotel has advised that the corridor contains a coat rack.',
    evidence: [
      {kind: 'testimony', quote: 'It was there and then I put the lamp on and it was not there.', speaker: 'Guest'},
    ],
    plausibility: 60, flags: ['possible-misidentification'],
    summary: 'Common peripheral-vision report, but the witness was awake and looking directly at the doorway.',
    memo: 'The silhouette was observed while the witness was looking directly at it, which distinguishes the file from the more usual peripheral report. The coat rack is noted and is not obviously the right shape. Recommended: Director’s review.',
    verdict: 'inconclusive', note: 'Coat rack a fair candidate. Direct-gaze observation is not explained. Filed as inconclusive.',
  },
  {
    n: 22, title: 'Knocking in the walls of the rented house', category: 'ghost', subject: 'poltergeist',
    region: 'salem-ma', offset: [0.003, -0.004], place: 'Rented house on a quiet street',
    observedAt: '2025-10-17T03:00:00Z', witness: '53D7', light: 'night', weather: 'wind', duration: 1800,
    description: 'Tenants report repeated knocking from inside the walls, always between 02:00 and 03:30, for three consecutive weeks. A kitchen cupboard door opened twice. The household comprises two adults and a dog. The dog is calm. The tenants have asked whether the Bureau can help, and, if not, whether it can recommend a plumber.',
    evidence: [
      {kind: 'sound', description: 'Rhythmic knocking in the wall, three or four knocks at a time.', seconds: 20},
    ],
    plausibility: 28, flags: ['possible-misidentification', 'weather-explains'],
    summary: 'Knocking pattern consistent with pipes expanding as the heating cycles off.',
    memo: 'Knocking at 02:00 to 03:30 in cold weather, in an older house, matches the timing of a boiler cycling down. The cupboard door has a worn catch. The dog’s lack of concern is, in the Bureau’s experience, the most reliable indicator on file. Recommended: Director’s review.',
    verdict: 'debunked', verdictBy: 'director', directorNote: 'Boiler cycling down. Water hammer in the wall. Cupboard catch worn. A plumber has been recommended, as requested.',
  },
  {
    n: 23, title: 'Figure in a window, reflected', category: 'ghost', subject: 'grey-lady',
    region: 'edinburgh-uk', offset: [0.003, -0.006], place: 'Upper window of a tenement',
    observedAt: '2021-12-19T15:00:00Z', witness: 'F2E4', light: 'dusk', weather: 'fog', distance: 20, duration: 5,
    description: 'Witness reports a female figure in an upper window of an unoccupied tenement. The figure was still and pale. The witness photographed the window and later noted that it faces the street where a woman had been standing.',
    evidence: [
      {kind: 'photo', key: 'c23-window', caption: 'The upper window, with a reflection of the street below'},
    ],
    plausibility: 15, flags: ['possible-misidentification', 'low-detail'],
    summary: 'Reflection of a passer-by in an upper window.',
    memo: 'The photograph shows a reflection of the street in the glass, including a woman on the pavement whose position matches the figure. The witness is a reliable source, as shown by Case 20, and this is a reasonable mistake in poor light. Routed for automatic closure.',
    verdict: 'debunked',
  },
  {
    n: 24, title: 'Tall dark figure on the landing, at the same time each night', category: 'ghost', subject: 'shadow-figure',
    region: 'salem-ma', offset: [-0.004, 0.002], place: 'Landing of a 19th-century townhouse',
    observedAt: '2026-05-09T06:10:00Z', witness: '3C68', light: 'night', weather: 'clear', distance: 5, duration: 15,
    description: 'Homeowner reports a tall dark figure standing on the upper landing at 01:10 on four consecutive nights. On the fourth night the homeowner set up a camera on the stairs. The camera recorded nothing and the homeowner recorded the camera. A neighbour confirms hearing the stairs creak on the same nights.',
    evidence: [
      {kind: 'testimony', quote: 'Four nights. Same time. It does not seem to mind me.', speaker: 'Homeowner'},
      {kind: 'sound', description: 'A slow creak on the fourth stair, twice, at 01:10.', seconds: 6},
    ],
    plausibility: 74, flags: ['strong-detail', 'multiple-witnesses'],
    summary: 'Repeatable timing, a corroborating neighbour, and a camera that recorded nothing.',
    memo: 'The regular timing and the neighbour’s independent account raise the file well above a single-witness report. A camera that records nothing is, in the Bureau’s view, more interesting than one that records something. Recommended for investigation.',
  },
  {
    n: 25, title: 'Knocking from the sealed storage room', category: 'spirit', subject: 'jinn',
    region: 'cairo-eg', offset: [0.01, -0.02], place: 'Family apartment, older building',
    observedAt: '2026-02-22T18:45:00Z', witness: 'D90F', light: 'artificial', weather: 'clear', duration: 900,
    description: 'A family of five reports repeated knocking from a sealed storage room in the evenings, and an occasional smell of smoke with no source. An elder relative states that the family believes a jinn is present in the apartment and asks that their belief be recorded as they hold it. The family has asked the Bureau not to explain it away. They are not asking for anything else.',
    evidence: [
      {kind: 'testimony', quote: 'We are not afraid. We would like it written down as we say it.', speaker: 'Family elder'},
      {kind: 'sound', description: 'Knocking from the storage room, unhurried, three at a time.', seconds: 30},
    ],
    plausibility: 50, flags: ['faith-sensitive'],
    summary: 'Family account recorded as given. The Bureau takes no position on matters of faith.',
    memo: 'The account is recorded in the family’s own words. The Bureau takes no position on matters of faith and offers no explanation of belief. For completeness only: the building is old, with shared ventilation and pipework, and the smell of smoke may correspond to a neighbouring kitchen. These observations are not offered in place of the family’s understanding. Routed to the Director for review.',
  },
  {
    n: 26, title: 'Voices in the archive room, at night', category: 'spirit', subject: 'jinn',
    region: 'istanbul-tr', offset: [0.005, 0.01], place: 'Municipal archive building, lower floor',
    observedAt: '2025-03-14T21:15:00Z', witness: 'A9C3', light: 'artificial', weather: 'clear', distance: 6, duration: 240,
    description: 'A night-shift security guard reports hearing voices from an empty archive room over several nights. Nobody was inside. He describes a presence he understood in the terms of his own faith, recited protective verses, and reports that the sounds stopped. He asks that the account be recorded accurately and respectfully. It is.',
    evidence: [
      {kind: 'testimony', quote: 'I did what my family taught me. It stopped. I want that written as it happened.', speaker: 'Security guard'},
      {kind: 'sound', description: 'Low voices from behind a closed door; the room was empty and locked.', seconds: 45},
    ],
    plausibility: 66, flags: ['faith-sensitive'],
    summary: 'Witness account recorded in his own terms. Room was empty and locked. The Bureau takes no position on matters of faith.',
    memo: 'The account is specific, calm and consistent across several nights. The room was verified empty and locked. The Bureau records the witness’s understanding of the event as he gave it and does not characterise it as mistaken. Routed to the Director for review.',
    verdict: 'classified', note: 'Recorded as reported. Room verified empty and locked. On file as unexplained. The Bureau takes no position on matters of faith.',
  },
  {
    n: 27, title: 'A warm, gentle presence in the guest room', category: 'spirit', subject: 'wandering-spirit',
    region: 'new-orleans-la', offset: [-0.006, 0.003], place: 'Guest room of a family home',
    observedAt: '2024-05-07T09:00:00Z', witness: '3C68', light: 'dusk', weather: 'clear', duration: 600,
    description: 'A guest reports a sense of warmth and quiet company in the room where a grandparent used to sleep, along with a faint scent of a familiar perfume. The guest describes the experience as comforting and asks for nothing except that it be recorded. The family is content with this.',
    evidence: [
      {kind: 'testimony', quote: 'It felt like being kept company. I was not frightened.', speaker: 'Guest'},
    ],
    plausibility: 57, flags: ['faith-sensitive'],
    summary: 'Gentle account, recorded in the witness’s own words. The Bureau takes no position on matters of faith.',
    memo: 'The account is short, calm and specific. The Bureau records it as given and offers no explanation of how the witness or the family understands it. Routed to the Director for review.',
    verdict: 'inconclusive', note: 'Recorded as reported. No observable factor identified and none sought. Filed as inconclusive.',
  },
  {
    n: 28, title: 'Silent gathering in a lodge that is on no register', category: 'occult', subject: 'secret-society-activity',
    region: 'providence-ri', offset: [0.004, 0.005], place: 'Three-storey hall on a side street',
    observedAt: '2026-07-11T02:00:00Z', witness: '8B1A', light: 'artificial', weather: 'rain', distance: 15, duration: 1500,
    description: 'Witness, a building surveyor, reports a lodge hall that appears on no property register. Through a ground-floor window, roughly forty people in grey coats held lanterns and stood in complete silence for 25 minutes. When questioned, a man at the door said "you have not seen this". The witness has since been unable to find the building. The hall is real. The Bureau has found only its name: the Order of the Hollow Lantern. The Order does not, to the Bureau’s knowledge, exist.',
    evidence: [
      {kind: 'testimony', quote: 'Forty people. Grey coats. Not one of them spoke. I timed it.', speaker: 'Surveyor'},
      {kind: 'photo', key: 'c28-lodge', caption: 'The hall entrance, side street, in the rain'},
    ],
    plausibility: 72, flags: ['strong-detail'],
    summary: 'Detailed observation of a coordinated silent gathering at an unregistered premises.',
    memo: 'The witness is a professional surveyor and his account of the premises is precise. A gathering of forty people who do not speak for 25 minutes is unusual on any measure. The Order of the Hollow Lantern is a fictional society in the Bureau’s files, and the file is written accordingly. No claim is made about any real organisation. Recommended for investigation.',
  },
  {
    n: 29, title: 'Circle of candles and salt in a clearing', category: 'occult', subject: 'ritual-site-activity',
    region: 'pine-barrens-nj', offset: [-0.03, -0.07], place: 'Forest clearing off a sand road',
    observedAt: '2025-06-21T05:00:00Z', witness: '61A8', light: 'dusk', weather: 'clear', distance: 40, duration: 300,
    description: 'Witness found a circle of about 30 candles with a line of salt across a clearing, and several people standing outside it in silence. The witness left and reported it. The candles were still burning at first light.',
    evidence: [
      {kind: 'photo', key: 'c29-circle', caption: 'Circle of candles and a line of salt, dusk'},
    ],
    plausibility: 24, flags: ['possible-misidentification', 'low-detail'],
    summary: 'A gathering with a bonfire permit and candles supplied by the venue.',
    memo: 'A private gathering had a valid fire permit for the same date and clearing. The candles were supplied in bulk by the organiser, and the salt is consistent with a food-and-drink table. No claim of ritual was made by anyone present. The Bureau records the arrangement and makes no comment on anyone’s beliefs. Recommended: Director’s review.',
    verdict: 'debunked', verdictBy: 'director', directorNote: 'Private gathering with a fire permit. Candles supplied by the venue. No ritual claimed. Closed.',
  },
  {
    n: 30, title: 'Ledger of a society that does not exist', category: 'occult', subject: 'secret-society-activity',
    region: 'washington-dc', offset: [0.006, -0.004], place: 'Municipal records annex',
    observedAt: '2026-08-04T14:30:00Z', witness: '53D7', light: 'artificial', weather: 'clear', distance: 2, duration: 900,
    description: 'Witness, a records clerk, found a bound ledger annotated with membership entries under the heading "Ninth Meridian". Entries run from 1932 to the present and appear in a consistent hand. The clerk photographed three pages and returned the ledger to its shelf. It was not on the shelf the following day. The Ninth Meridian Society is a fictional society in the Bureau’s files.',
    evidence: [
      {kind: 'testimony', quote: 'The handwriting never changes. Ninety years, one hand.', speaker: 'Records clerk'},
      {kind: 'photo', key: 'c30-ledger', caption: 'Three pages of the ledger, photographed at the shelf'},
    ],
    plausibility: 72, flags: ['strong-detail'],
    summary: 'Documentary evidence of a long-running membership record; the ledger has since been removed.',
    memo: 'The photographs show a consistent hand across nine decades, which is unusual for any record and remarkable for a membership ledger. The ledger’s disappearance is noted and is not, in itself, evidence of anything. The Bureau’s file on the Ninth Meridian Society is fictional and no claim is made about any real group. Recommended for investigation.',
    verdict: 'classified', note: 'Photographic record obtained. Ledger since removed. On file as unexplained.',
  },
]
