import type {SeedCase} from './types'

// Cases 01-15: cryptid (01-08) and UFO (09-15).
export const CASES_A: SeedCase[] = [
  {
    n: 1, title: 'Tall figure crossing Route 101 at dusk', category: 'cryptid', subject: 'sasquatch',
    region: 'olympic-wa', offset: [-0.31, 0.22], place: 'Route 101, north of Kalaloch',
    observedAt: '2023-10-14T01:40:00Z', witness: '4F2A', light: 'dusk', weather: 'fog', distance: 40, duration: 12,
    description: 'Witness was driving north at approximately 45 mph when a bipedal figure crossed the road about 40 metres ahead. Estimated height 2.4 metres, covered in dark hair. The figure did not run. It walked. Witness stopped, engaged hazard lights and observed for roughly 12 seconds before the figure entered the treeline. Witness notes the figure "did not appear to be in a hurry". The dashcam was, regrettably, not recording.',
    evidence: [
      {kind: 'footprint', lengthCm: 41},
      {kind: 'photo', key: 'c01-print', caption: 'Footprint impression at the road shoulder, photographed the following morning'},
      {kind: 'testimony', quote: 'It looked at me like I was the one who was out of place.', speaker: 'Witness'},
    ],
    plausibility: 84, flags: ['strong-detail'],
    summary: 'Credible daylight-adjacent sighting with a physical trace and a consistent account.',
    memo: 'The witness account is specific, unhurried and free of embellishment. Height estimate is consistent with the width of the roadway. A footprint impression of 41 cm was recovered from the shoulder. No competing explanation fits the stride length described. Recommended for investigation.',
    verdict: 'classified', note: 'Footprint cast is consistent with three earlier files. Stride length rules out a person in costume. Filed as unexplained.',
  },
  {
    n: 2, title: 'Large figure at campsite, footprints "too small"', category: 'cryptid', subject: 'sasquatch',
    region: 'olympic-wa', offset: [0.12, -0.18], place: 'Hoh Rainforest campground',
    observedAt: '2024-06-02T05:20:00Z', witness: '9C1D', light: 'night', weather: 'rain', distance: 25, duration: 40,
    description: 'Witness heard heavy movement outside the tent at approximately 22:20 and shone a torch toward the noise. A large dark shape stood upright for around 40 seconds, then dropped to all fours and left. Witness measured footprints in the morning and found them smaller than expected, at 17 cm, and with visible claw marks.',
    evidence: [
      {kind: 'footprint', lengthCm: 17},
      {kind: 'testimony', quote: 'I was sure it was standing. Then it was not standing.', speaker: 'Witness'},
    ],
    plausibility: 31, flags: ['animal-explains', 'possible-misidentification'],
    summary: 'Behaviour and footprints are consistent with a black bear.',
    memo: 'A 17 cm print with claw marks is a bear print. The upright posture followed by a drop to all fours is a known bear behaviour when investigating a smell of food. The witness did not report a food storage container. Recommended: Director’s review.',
    verdict: 'debunked', verdictBy: 'director', directorNote: 'Black bear. Claw marks and print size settle it. The Bureau suggests a bear canister.',
  },
  {
    n: 3, title: 'Winged figure over the Silver Bridge site', category: 'cryptid', subject: 'mothman',
    region: 'point-pleasant-wv', offset: [0.02, 0.03], place: 'Ohio River bank near the memorial',
    observedAt: '2025-11-08T03:10:00Z', witness: 'B07E', light: 'artificial', weather: 'clear', distance: 60, duration: 20,
    description: 'Witness, a night-shift delivery driver, stopped near the river to check a tyre. A large winged figure passed low overhead, silent, with two red points of light at head height that brightened as it passed a streetlamp. Wingspan estimated at over two metres. Witness reports an immediate feeling that "something was about to happen". Nothing happened. Witness has asked us to note that this is the worst part.',
    evidence: [
      {kind: 'testimony', quote: 'No sound. Big as a door. Two red lights, like a car in the rain.', speaker: 'Witness'},
      {kind: 'sound', description: 'Witness heard a dry rustling, then nothing, before the figure appeared.', seconds: 6},
    ],
    plausibility: 78, flags: ['strong-detail'],
    summary: 'Detailed report with the classic reflective-eye feature at a location with a long file history.',
    memo: 'Account is consistent with 14 earlier reports from the same stretch of river. The reflective eyes are a well-recorded feature and the witness could not have been expected to know it. The Bureau notes the possibility of a large owl or heron and has requested nothing further from the witness. Recommended for investigation.',
  },
  {
    n: 4, title: 'Screaming creature in the cedar swamp', category: 'cryptid', subject: 'jersey-devil',
    region: 'pine-barrens-nj', offset: [-0.08, 0.1], place: 'Cedar swamp trail, Wharton State Forest',
    observedAt: '2022-09-17T02:30:00Z', witness: '61A8', light: 'night', weather: 'clear', distance: 90, duration: 300,
    description: 'Two hikers, camping off-trail, heard a sustained shriek from the swamp at approximately 22:30 and again 40 minutes later. One hiker briefly saw a dark shape crossing a clearing with an upright posture and what she described as "folded wings". No clear view was obtained. The second hiker did not see anything and would like that on the record.',
    evidence: [
      {kind: 'sound', description: 'Two shrieks, second one closer, lasting roughly 4 seconds each.', seconds: 8},
      {kind: 'testimony', quote: 'I saw a shape, not a creature. I want to be accurate.', speaker: 'Witness'},
    ],
    plausibility: 55, flags: ['low-detail', 'possible-misidentification'],
    summary: 'Audio account plausible but a fox or barred owl cannot be excluded; visual is brief.',
    memo: 'A fox’s scream is the leading candidate and is frequently reported as alarming. The visual account is brief and made at 90 metres in darkness. The witness’s care about the limits of what she saw is noted and, in the Bureau’s view, is the most credible feature of the file. Recommended: Director’s review.',
    verdict: 'inconclusive', note: 'Audio consistent with a fox but not diagnostic. The upright shape remains unexplained. Filed as inconclusive.',
  },
  {
    n: 5, title: 'Livestock predator behind the feed store', category: 'cryptid', subject: 'chupacabra',
    region: 'puerto-rico', offset: [0.06, -0.2], place: 'Farm outside Aibonito',
    observedAt: '2021-03-11T11:00:00Z', witness: 'D3F0', light: 'dusk', weather: 'clear', distance: 15, duration: 60,
    description: 'Farmer reports finding two chickens dead with small puncture marks and observed a hairless, grey-skinned animal with a spiny ridge along its back near the coop. The animal ran on four legs when approached. Farmer photographed it from a distance of 15 metres.',
    evidence: [
      {kind: 'photo', key: 'c05-animal', caption: 'The animal, moments before it left the property'},
    ],
    plausibility: 12, flags: ['animal-explains', 'known-hoax-pattern'],
    summary: 'Hairless four-legged animal with skin condition, consistent with a mangy coyote.',
    memo: 'Hairless skin, grey pigmentation and a visible spine ridge are typical of advanced mange in canines. This description matches every recovered specimen on file. The chicken losses are consistent with any small predator. Routed for automatic closure.',
    verdict: 'debunked',
  },
  {
    n: 6, title: 'Long-necked shape in calm water', category: 'cryptid', subject: 'loch-ness-monster',
    region: 'loch-ness-uk', offset: [-0.05, 0.02], place: 'Loch shore near Urquhart',
    observedAt: '2026-08-21T14:15:00Z', witness: '2E9B', light: 'daylight', weather: 'clear', distance: 420, duration: 180,
    description: 'Witness on the shore observed a dark, elongated shape moving against the direction of the surface ripple for about three minutes. The shape had a raised section that the witness estimated at 1.5 metres. No boat traffic was visible. A second observer, on the far bank, has not been located.',
    evidence: [
      {kind: 'photo', key: 'c06-wake', caption: 'The shape, 420 metres out, a small dark mark on flat water'},
      {kind: 'testimony', quote: 'It was going the wrong way for a log.', speaker: 'Witness'},
    ],
    plausibility: 47, flags: ['possible-misidentification', 'low-detail'],
    summary: 'Distant observation of a slow shape in calm water. Log, wake or otter cannot be ruled out.',
    memo: 'Observation distance of 420 metres is at the limit where floating debris becomes convincing. The witness’s point about direction is fair: a log moves with the current, and the loch has several. The photograph does not settle it. Recommended: Director’s review.',
  },
  {
    n: 7, title: 'Foul smell and upright figure at the boardwalk', category: 'cryptid', subject: 'skunk-ape',
    region: 'everglades-fl', offset: [0.03, 0.05], place: 'Boardwalk near Loop Road',
    observedAt: '2024-02-19T22:00:00Z', witness: '4F2A', light: 'dusk', weather: 'clear', distance: 30, duration: 25,
    description: 'Witness smelled a strong sulphurous odour for several minutes before an upright, reddish-haired figure crossed the boardwalk ahead. The figure was estimated at 2 metres tall and moved into shallow water without apparent effort. Witness also filed Case 01 in the Pacific North-west. The Bureau notes the coincidence and the witness’s remarkable itinerary.',
    evidence: [
      {kind: 'footprint', lengthCm: 36},
      {kind: 'testimony', quote: 'The smell arrived first. That is how I knew before I saw.', speaker: 'Witness'},
    ],
    plausibility: 73, flags: ['strong-detail', 'multiple-witnesses'],
    summary: 'Detailed sensory account with a physical trace; prior file history for the witness is consistent.',
    memo: 'A second party on the boardwalk independently reported the odour, which raises the file above a single-witness account. The footprint length is within the range of the subject file. The witness’s prior report (Case 01) is treated as corroboration of credibility, not of the event. Recommended for investigation.',
    verdict: 'classified', note: 'Odour corroborated by a second party. Footprint on file. Recorded as unexplained.',
  },
  {
    n: 8, title: 'Winged creature seen at a gas station', category: 'cryptid', subject: 'jersey-devil',
    region: 'pine-barrens-nj', offset: [0.1, -0.05], place: 'Route 72 rest stop',
    observedAt: '2020-10-31T06:00:00Z', witness: '7A44', light: 'artificial', weather: 'clear', distance: 8, duration: 15,
    description: 'Witness reports a large winged figure with horns standing next to the air pump. It waved. Witness has since been informed that Halloween falls on the same date. Witness maintains the figure was "very committed".',
    evidence: [
      {kind: 'photo', key: 'c08-figure', caption: 'The figure by the air pump'},
    ],
    plausibility: 9, flags: ['known-hoax-pattern', 'possible-misidentification'],
    summary: 'Costumed person at a rest stop on 31 October.',
    memo: 'The figure waved, wore visible boots and stood next to an air pump on the one night of the year when this is the most probable explanation. The photograph shows a zip. The Bureau congratulates the costume. Routed for automatic closure.',
    verdict: 'debunked',
  },
  {
    n: 9, title: 'Silent triangle over the Extraterrestrial Highway', category: 'ufo', subject: 'silent-triangle',
    region: 'rachel-nv', offset: [-0.12, 0.2], place: 'State Route 375, mile marker 28',
    observedAt: '2024-07-04T04:50:00Z', witness: 'C5D2', light: 'night', weather: 'clear', distance: 300, duration: 95, shape: 'triangle',
    description: 'Witness and a passenger, driving at night, observed a large dark triangular object moving slowly and silently above the highway at an estimated altitude of 300 metres. Three dim white lights at the corners. The object blocked out the stars as it passed. Vehicle radio, which was on, did not change. Duration of the observation was 95 seconds.',
    evidence: [
      {kind: 'testimony', quote: 'It did not reflect anything. It just removed stars.', speaker: 'Witness'},
      {kind: 'photo', key: 'c09-triangle', caption: 'Three lights at the corners, taken through the windscreen'},
    ],
    plausibility: 88, flags: ['strong-detail', 'multiple-witnesses'],
    summary: 'Two independent observers, unusual duration, no aircraft signature.',
    memo: 'Two observers agree on shape, lighting and the absence of sound over a period of 95 seconds. No scheduled aircraft was operating in the area at the time. The Bureau notes the proximity of restricted airspace and offers no comment. Recommended for investigation.',
    verdict: 'classified', note: 'No matching aircraft movement. Two-party account. Filed as unexplained.',
  },
  {
    n: 10, title: 'White capsule-shaped object near the perimeter', category: 'ufo', subject: 'tic-tac-object',
    region: 'area51', offset: [0.05, 0.11], place: 'Public road, south of the boundary warning signs',
    observedAt: '2025-05-16T03:30:00Z', witness: '18FE', light: 'night', weather: 'clear', distance: 800, duration: 40, shape: 'tic-tac',
    description: 'Witness, a hiker, observed a smooth white capsule-shaped object approximately 12 metres long hovering at low altitude beyond the boundary signage. No wings, rotors or exhaust were visible. It accelerated horizontally in less than two seconds and was out of view. Two vehicles with tinted windows arrived shortly afterwards. Witness was asked to move along. Witness moved along.',
    evidence: [
      {kind: 'testimony', quote: 'Whatever it was, it did not need a runway.', speaker: 'Witness'},
      {kind: 'photo', key: 'c10-capsule', caption: 'White object over the ridge line'},
    ],
    plausibility: 81, flags: ['strong-detail'],
    summary: 'Distinct object description consistent with the subject file, at a restricted site.',
    memo: 'The observed acceleration and shape match the subject file. The presence of a security response is noted. The witness followed instructions and is commended for it. Recommended for investigation. Please note this file is subject to the usual restrictions on where a file may be discussed.',
  },
  {
    n: 11, title: 'Line of glowing lights crossing the red rocks', category: 'ufo', subject: 'luminous-orb-cluster',
    region: 'sedona-az', offset: [0.03, -0.06], place: 'Airport Mesa viewpoint',
    observedAt: '2026-01-09T02:12:00Z', witness: 'A9C3', light: 'night', weather: 'clear', duration: 240, shape: 'light-only',
    description: 'A group of witnesses on a viewpoint observed a line of approximately 30 evenly spaced white lights moving in single file across the sky from west to east at a steady pace. No sound. The lights faded out one by one at the eastern horizon.',
    evidence: [
      {kind: 'photo', key: 'c11-lights', caption: 'Line of lights, long exposure'},
    ],
    plausibility: 14, flags: ['satellite-explains', 'celestial-explains'],
    summary: 'Satellite train. Timing matches a launch deployment 3 days earlier.',
    memo: 'A steady single-file procession of lights that fade at the same point in the sky is the signature of a satellite train leaving Earth’s shadow. A deployment matching the timing is on public record. The Bureau appreciates the witnesses’ report and the quality of the photograph. Routed for automatic closure.',
    verdict: 'debunked',
  },
  {
    n: 12, title: 'Metallic disc hovering above the mesa', category: 'ufo', subject: 'classic-disc',
    region: 'roswell-nm', offset: [-0.1, 0.08], place: 'Ranch road north of town',
    observedAt: '2022-07-08T00:45:00Z', witness: '7A44', light: 'daylight', weather: 'wind', distance: 1500, duration: 300, shape: 'disc',
    description: 'Witness observed a silver disc-shaped object hanging motionless above a mesa for approximately five minutes. It rocked slightly and reflected sunlight. It then descended out of view. Witness notes wind conditions were strong that day.',
    evidence: [
      {kind: 'photo', key: 'c12-disc', caption: 'Small silver disc over the mesa'},
    ],
    plausibility: 26, flags: ['weather-explains', 'aircraft-explains'],
    summary: 'A weather balloon released from the regional airport that afternoon.',
    memo: 'A silver object that rocks in strong wind, holds position and then descends is a weather balloon, which the local airport released at 17:30. The Bureau notes that this is what the object was in 1947 as well, and that no one has ever been persuaded by it. Recommended: Director’s review.',
    verdict: 'debunked', verdictBy: 'director', directorNote: 'Weather balloon launched at 17:30. Same balloon type. Same result.',
  },
  {
    n: 13, title: 'Triangular craft pacing a car on the desert road', category: 'ufo', subject: 'silent-triangle',
    region: 'area51', offset: [-0.04, -0.09], place: 'Dirt road west of the boundary',
    observedAt: '2026-03-27T05:05:00Z', witness: '18FE', light: 'night', weather: 'clear', distance: 200, duration: 180, shape: 'triangle',
    description: 'Witness reports a triangular dark object that paced the vehicle for about three minutes at a lateral distance of 200 metres, matching the car’s speed of 30 mph. Lights at the corners. When the witness stopped, the object stopped. When the witness started, it started. Witness would like the Bureau to know this was not a comfortable drive.',
    evidence: [
      {kind: 'testimony', quote: 'I stopped and it stopped. That is the part I keep coming back to.', speaker: 'Witness'},
    ],
    plausibility: 52, flags: ['aircraft-explains', 'low-detail'],
    summary: 'Pacing behaviour is notable; a drone or aircraft cannot be ruled out. Second file from this witness.',
    memo: 'The stop-and-start behaviour is the item of interest. A drone operating in the area would behave this way. The witness filed Case 10 ten months earlier and is treated as reliable. The file is held for review pending a check of operator records. Recommended: Director’s review.',
  },
  {
    n: 14, title: 'Cluster of pulsing orbs above the ridge', category: 'ufo', subject: 'luminous-orb-cluster',
    region: 'rachel-nv', offset: [0.08, -0.1], place: 'Desert pull-off near mile marker 32',
    observedAt: '2023-09-22T04:20:00Z', witness: 'C5D2', light: 'night', weather: 'clear', distance: 2000, duration: 420, shape: 'sphere',
    description: 'Witness observed five amber orbs in a loose group above a ridge line, pulsing slowly in brightness. Two drifted out of the group and rejoined. They remained visible for seven minutes and then went out together. Witness is the same person as in Case 09 and asks that this be considered "a different night".',
    evidence: [
      {kind: 'photo', key: 'c14-orbs', caption: 'Five amber orbs over the ridge'},
    ],
    plausibility: 58, flags: ['celestial-explains', 'low-detail'],
    summary: 'Amber pulsing lights, drifting group. Flares or lanterns are possible; no source identified.',
    memo: 'Amber colour and slow pulsing suggest flares or sky lanterns, though the group behaviour is unusual. The witness’s previous report (Case 09) was credible. No scheduled flare activity was found in the area. Recommended: Director’s review.',
    verdict: 'inconclusive', note: 'No release or launch on record. Lantern drift pattern is a fair match but unproven. Filed as inconclusive.',
  },
  {
    n: 15, title: 'Capsule-shaped object above the test range', category: 'ufo', subject: 'tic-tac-object',
    region: 'area51', offset: [0.08, 0.04], place: 'Public viewing area on the perimeter road',
    observedAt: '2025-09-30T04:00:00Z', witness: 'E60B', light: 'dusk', weather: 'clear', distance: 1200, duration: 22, shape: 'tic-tac',
    description: 'Witness observed a white capsule-shaped object at an estimated altitude of 3,000 metres. It moved north at high speed, stopped abruptly, then moved east at a right angle. No trail. Duration of the observation 22 seconds.',
    evidence: [
      {kind: 'testimony', quote: 'It stopped like it had changed its mind.', speaker: 'Witness'},
    ],
    plausibility: 76, flags: ['strong-detail'],
    summary: 'Right-angle course change at speed, consistent with the subject file.',
    memo: 'The right-angle turn at speed is the feature that distinguishes this account from ordinary aircraft. The witness is a repeat filer (see Cases 16 and 19) whose accounts have been consistent. Recommended for investigation.',
    verdict: 'classified', note: 'Consistent with the subject file. Course change is not explained by any aircraft on record. Filed as unexplained.',
  },
]
